version: "0.1"

subdomains:
  aspnet-subdomain:
    module: nullstone/autogen-aws-subdomain

apps:
  aspnet-quickstart:
    module: nullstone/aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 9000
    capabilities:
      - module: nullstone/aws-load-balancer
        connections:
          subdomain: aspnet-subdomain
